import React from 'react';

export const sqlSchema = `-- 1. Habilitar extensões necessárias
create extension if not exists "uuid-ossp" with schema "extensions";

-- 2. Tabela de Configurações (Garante que o site carregue)
create table if not exists public.settings (
  id bigint primary key generated by default as identity,
  settings_data jsonb not null
);
insert into public.settings (id, settings_data) values (1, '{}') on conflict (id) do nothing;
alter table public.settings enable row level security;
drop policy if exists "Public read access" on public.settings;
create policy "Public read access" on public.settings for select using (true);
drop policy if exists "Admin write access" on public.settings;
create policy "Admin write access" on public.settings for all using (auth.uid() is not null);

-- 3. Tabela de Serviços
create table if not exists public.services (
  id uuid primary key default uuid_generate_v4(),
  title text not null,
  description text not null,
  image_url text,
  price numeric,
  show_price boolean default true,
  requirements text,
  document_checklist text[],
  created_at timestamptz default now() not null
);
alter table public.services enable row level security;
drop policy if exists "Allow public read access to services" on public.services;
create policy "Allow public read access to services" on public.services for select using (true);
drop policy if exists "Allow admin full access to services" on public.services;
create policy "Allow admin full access to services" on public.services for all using (auth.uid() is not null);

-- 4. Tabela de Notícias
create table if not exists public.posts (
  id uuid primary key default uuid_generate_v4(),
  title text not null,
  summary text not null,
  content text not null,
  image_url text,
  created_at timestamptz default now() not null
);
alter table public.posts enable row level security;
drop policy if exists "Allow public read access to posts" on public.posts;
create policy "Allow public read access to posts" on public.posts for select using (true);
drop policy if exists "Allow admin full access to posts" on public.posts;
create policy "Allow admin full access to posts" on public.posts for all using (auth.uid() is not null);

-- 5. Tabela de Produtos (PCE)
create table if not exists public.products (
  id uuid primary key default uuid_generate_v4(),
  nome_completo text not null,
  marca text,
  modelo text,
  calibre text,
  capacidade_municao numeric,
  preco numeric,
  descricao_longa text,
  pce boolean default true,
  featured boolean default false,
  imagem_capa_url text,
  created_at timestamptz default now() not null
);
alter table public.products enable row level security;
drop policy if exists "Allow public read access to products" on public.products;
create policy "Allow public read access to products" on public.products for select using (true);
drop policy if exists "Allow admin full access to products" on public.products;
create policy "Allow admin full access to products" on public.products for all using (auth.uid() is not null);

-- 6. CONFIGURAÇÃO DE IMAGENS (STORAGE)
-- Garante que o container 'assets' existe
insert into storage.buckets (id, name, public)
values ('assets', 'assets', true)
on conflict (id) do nothing;

-- Remove políticas antigas (Sintaxe correta para DROP)
drop policy if exists "Public read access for assets" on storage.objects;
drop policy if exists "Admin can upload to assets" on storage.objects;
drop policy if exists "Admin can update assets" on storage.objects;
drop policy if exists "Admin can delete assets" on storage.objects;

-- Cria novas políticas de acesso para imagens
create policy "Public read access for assets" on storage.objects for select using ( bucket_id = 'assets' );
create policy "Admin can upload to assets" on storage.objects for insert with check ( bucket_id = 'assets' );
create policy "Admin can update assets" on storage.objects for update using ( bucket_id = 'assets' );
create policy "Admin can delete assets" on storage.objects for delete using ( bucket_id = 'assets' );

-- 7. Tabela de Clientes
create table if not exists public.clients (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  email text not null,
  cpf text not null unique,
  phone text,
  address jsonb,
  birth_date text,
  rg text,
  gov_password_info text,
  processes jsonb,
  created_at timestamptz default now() not null
);
alter table public.clients enable row level security;
drop policy if exists "Allow admin full access to clients" on public.clients;
create policy "Allow admin full access to clients" on public.clients for all using (auth.uid() is not null);`;

const SetupGuide: React.FC = () => {
    const copyToClipboard = () => {
        navigator.clipboard.writeText(sqlSchema);
        alert("Script SQL corrigido copiado! Vá ao Supabase > SQL Editor e cole lá.");
    };

    return (
        <div className="min-h-screen bg-slate-900 flex flex-col justify-center py-12 px-4 sm:px-6 lg:px-8 font-sans">
            <div className="max-w-3xl mx-auto w-full bg-white rounded-3xl shadow-2xl overflow-hidden">
                <div className="bg-brand-navy p-8 text-center text-white">
                    <h2 className="text-3xl font-bold uppercase tracking-tight">Manutenção do Portal</h2>
                    <p className="mt-2 text-blue-100">Atualização de Banco de Dados e Imagens</p>
                </div>
                <div className="p-8 space-y-6">
                    <div className="bg-blue-50 border-l-4 border-blue-400 p-4">
                        <p className="text-sm text-blue-800 font-bold">Instruções:</p>
                        <p className="text-xs text-blue-600 mt-1">
                            Este código corrigido libera o salvamento de fotos e a tabela de produtos.
                        </p>
                    </div>
                    <div>
                        <textarea
                            readOnly
                            value={sqlSchema}
                            className="w-full h-64 p-4 bg-gray-900 text-green-400 font-mono text-xs rounded-xl focus:outline-none border-2 border-gray-800"
                            onClick={(e) => e.currentTarget.select()}
                        />
                        <button onClick={copyToClipboard} className="mt-4 w-full py-4 bg-blue-600 text-white font-bold rounded-xl hover:bg-blue-700 shadow-xl transition-all">
                            COPIAR CÓDIGO SQL CORRIGIDO
                        </button>
                    </div>
                    <div className="border-t pt-6 flex gap-4">
                        <a href="https://app.supabase.com" target="_blank" rel="noreferrer" className="flex-1 text-center py-3 border-2 border-gray-200 rounded-xl font-bold text-gray-700 hover:bg-gray-50">SUPABASE ↗</a>
                        <button onClick={() => window.location.reload()} className="flex-1 py-3 bg-brand-navy text-white font-bold rounded-xl">RECARREGAR SITE</button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default SetupGuide;
